// frontend-react/src/components/AgeGate.jsx
// frontend/src/components/AgeGate.jsx
import { useState, useEffect } from 'react';
import './AgeGate.css'; // Crearemos esto después

const AgeGate = () => {
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    // Verificamos si ya validó su edad anteriormente
    const isVerified = localStorage.getItem('ageVerified');
    if (!isVerified) {
      setShowModal(true);
    }
  }, []);

  const handleYes = () => {
    // Guardamos en el navegador que el usuario es mayor
    localStorage.setItem('ageVerified', 'true');
    setShowModal(false);
  };

  const handleNo = () => {
    // Si dice que NO, lo mandamos a Google o mostramos un mensaje
    window.location.href = "https://www.google.com";
  };

  if (!showModal) return null;

  return (
    <div className="age-gate-overlay">
      <div className="age-gate-box">
        <div className="warning-icon">🔞</div>
        <h2>Verificación de Edad</h2>
        <p>
          Debes tener 18 años o más para entrar a este sitio.
          Los productos contienen nicotina, una sustancia adictiva.
        </p>
        <p><strong>¿Eres mayor de edad?</strong></p>
        
        <div className="age-buttons">
          <button onClick={handleNo} className="btn-no">NO, SALIR</button>
          <button onClick={handleYes} className="btn-yes">SÍ, ENTRAR</button>
        </div>
      </div>
    </div>
  );
};

export default AgeGate;

// frontend/src/components/AgeGate.vue
<script setup>
import { ref, onMounted } from 'vue'

const showModal = ref(false)

onMounted(() => {
  const isVerified = localStorage.getItem('ageVerified')
  if (!isVerified) {
    showModal.value = true
  }
})

function handleYes() {
  localStorage.setItem('ageVerified', 'true')
  showModal.value = false
}

function handleNo() {
  window.location.href = "https://www.google.com"
}
</script>

<template>
  <div v-if="showModal" class="age-gate-overlay">
    <div class="age-gate-box">
      <div class="warning-icon">🔞</div>
      <h2>Verificación de Edad</h2>
      <p>
        Debes tener 18 años o más para entrar a este sitio.
        Los productos contienen nicotina, una sustancia adictiva.
      </p>
      <p><strong>¿Eres mayor de edad?</strong></p>
      
      <div class="age-buttons">
        <button @click="handleNo" class="btn-no">NO, SALIR</button>
        <button @click="handleYes" class="btn-yes">SÍ, ENTRAR</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.age-gate-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(0, 0, 0, 0.9);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 9999;
  backdrop-filter: blur(5px);
}

.age-gate-box {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  text-align: center;
  max-width: 400px;
  box-shadow: 0 4px 20px rgba(0,0,0,0.5);
}

.warning-icon {
  font-size: 3rem;
  margin-bottom: 1rem;
}

h2 {
  color: #d32f2f;
  margin-top: 0;
}

.age-buttons {
  display: flex;
  justify-content: space-around;
  margin-top: 2rem;
  gap: 1rem;
}

button {
  padding: 0.8rem 1.5rem;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-weight: bold;
  transition: transform 0.2s;
}

button:hover {
  transform: scale(1.05);
}

.btn-yes {
  background-color: #2e7d32;
  color: white;
}

.btn-no {
  background-color: #c62828;
  color: white;
}
</style>
