// frontend-react/src/components/PayPalCheckout.jsx
// frontend/src/components/PayPalCheckout.jsx
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";
import { useCart } from "../context/CartContext";
import { useNavigate } from "react-router-dom";

const PayPalCheckout = ({ total }) => {
  const { clearCart } = useCart();
  const navigate = useNavigate();

  return (
    <div style={{ marginTop: '20px', minWidth: '300px' }}>
      {/* Configuración inicial de PayPal */}
      <PayPalScriptProvider options={{ 
          "client-id": "AdfVJVM8RIQZblsMGD8VsJmCcNUpYg5i1QNFqyHPJ3k2DbG82VCIwbgBHbGges8o-AF76kzqdGCFs9K5", 
          currency: "USD"
      }}>
        <PayPalButtons 
          style={{ layout: "vertical" }}
          
          // 1. Crear la orden: Le decimos a PayPal cuánto cobrar
          createOrder={(data, actions) => {
            return actions.order.create({
              purchase_units: [
                {
                  amount: {
                    value: total.toFixed(2), // El total que viene del carrito
                  },
                },
              ],
            });
          }}

          // 2. Cuando el usuario aprueba el pago (se loguea y paga)
          onApprove={(data, actions) => {
            return actions.order.capture().then((details) => {
              const payerName = details.payer.name.given_name;
              alert(`✅ Pago realizado con éxito por ${payerName}`);
              
              // Limpiamos el carrito y volvemos al inicio
              clearCart();
              navigate("/");
            });
          }}
          
          // 3. Si hay error
          onError={(err) => {
            console.error("Error en PayPal:", err);
            alert("Hubo un error procesando el pago. Intenta de nuevo.");
          }}
        />
      </PayPalScriptProvider>
    </div>
  );
};

export default PayPalCheckout;

// frontend/src/components/PayPalCheckout.vue
<script setup>
import { ref, onMounted } from 'vue'
import { loadScript } from "@paypal/paypal-js"
import { useCartStore } from '../stores/cart'
import { useRouter } from 'vue-router'

const props = defineProps({
  total: {
    type: Number,
    required: true
  }
})

const cartStore = useCartStore()
const router = useRouter()
const paypalContainer = ref(null)

onMounted(async () => {
  try {
    const paypal = await loadScript({ 
      "client-id": "AdfVJVM8RIQZblsMGD8VsJmCcNUpYg5i1QNFqyHPJ3k2DbG82VCIwbgBHbGges8o-AF76kzqdGCFs9K5",
      currency: "USD"
    })

    if (paypal) {
      await paypal.Buttons({
        style: { layout: "vertical" },
        
        createOrder: (data, actions) => {
          return actions.order.create({
            purchase_units: [
              {
                amount: {
                  value: props.total.toFixed(2), // Usamos el valor actual del prop
                },
              },
            ],
          })
        },

        onApprove: async (data, actions) => {
          const details = await actions.order.capture()
          const payerName = details.payer.name.given_name
          alert(`✅ Pago realizado con éxito por ${payerName}`)
          
          cartStore.clearCart()
          router.push("/")
        },

        onError: (err) => {
          console.error("Error en PayPal:", err)
          alert("Hubo un error procesando el pago. Intenta de nuevo.")
        }
      }).render(paypalContainer.value)
    }
  } catch (error) {
    console.error("failed to load the PayPal JS SDK script", error)
  }
})
</script>

<template>
  <div class="paypal-wrapper">
    <p class="payment-label">Elige tu método de pago:</p>
    <div ref="paypalContainer"></div>
  </div>
</template>

<style scoped>
.paypal-wrapper {
  margin-top: 20px;
  min-width: 300px;
}
.payment-label {
    margin-bottom: 10px;
    font-size: 0.9rem;
    color: #666;
}
</style>
